In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
l1 = [1,21,3,"deep"]

In [7]:
a1 = np.array(l1)
a1

array(['1', '21', '3', 'deep'], dtype='<U11')

In [20]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [10]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
a1.ndim

1

In [21]:
a2.ndim

2

In [13]:
a3.ndim

3

In [15]:
a1.size

4

In [16]:
a2.size

6

In [17]:
a3.size

9

In [24]:
a1.shape

(4,)

In [25]:
a2.shape

(2, 3)

In [26]:
a3.shape

(1, 3, 3)

In [38]:
np.random.randint(2,50,(2,3,4))

array([[[11, 19, 23, 22],
        [26, 27, 18, 12],
        [48, 24, 25, 34]],

       [[ 8, 39, 17, 30],
        [18, 46, 29, 46],
        [47, 13, 10, 46]]])

In [41]:
np.random.rand(2,3)

array([[0.56805458, 0.84546317, 0.92384751],
       [0.80094686, 0.54666005, 0.77967435]])

In [42]:
np.random.randn(3,4)

array([[ 0.18467236, -0.08344175,  1.09355838,  1.04542603],
       [ 0.93358433,  0.31080783,  0.17857257,  0.36905268],
       [-0.79255872, -0.13838609,  0.34639662, -1.00930253]])

In [43]:
a4 = np.random.randn(4,4)

In [44]:
a4

array([[-0.25925705,  0.31604446,  0.90458417,  0.99250751],
       [ 1.19424638,  1.13476893,  1.0095084 ,  0.3378922 ],
       [ 1.57515511, -0.53424844, -0.06119531, -0.80808981],
       [ 0.86430324, -0.16651776,  0.07796355, -1.53232841]])

In [46]:
a4.reshape(2,8)

array([[-0.25925705,  0.31604446,  0.90458417,  0.99250751,  1.19424638,
         1.13476893,  1.0095084 ,  0.3378922 ],
       [ 1.57515511, -0.53424844, -0.06119531, -0.80808981,  0.86430324,
        -0.16651776,  0.07796355, -1.53232841]])

In [47]:
a4.reshape(8,2)

array([[-0.25925705,  0.31604446],
       [ 0.90458417,  0.99250751],
       [ 1.19424638,  1.13476893],
       [ 1.0095084 ,  0.3378922 ],
       [ 1.57515511, -0.53424844],
       [-0.06119531, -0.80808981],
       [ 0.86430324, -0.16651776],
       [ 0.07796355, -1.53232841]])

In [48]:
a4.reshape(16,1)

array([[-0.25925705],
       [ 0.31604446],
       [ 0.90458417],
       [ 0.99250751],
       [ 1.19424638],
       [ 1.13476893],
       [ 1.0095084 ],
       [ 0.3378922 ],
       [ 1.57515511],
       [-0.53424844],
       [-0.06119531],
       [-0.80808981],
       [ 0.86430324],
       [-0.16651776],
       [ 0.07796355],
       [-1.53232841]])

In [49]:
a4.reshape(2,-1)

array([[-0.25925705,  0.31604446,  0.90458417,  0.99250751,  1.19424638,
         1.13476893,  1.0095084 ,  0.3378922 ],
       [ 1.57515511, -0.53424844, -0.06119531, -0.80808981,  0.86430324,
        -0.16651776,  0.07796355, -1.53232841]])

In [50]:
a4.reshape(2,-567576876789)

array([[-0.25925705,  0.31604446,  0.90458417,  0.99250751,  1.19424638,
         1.13476893,  1.0095084 ,  0.3378922 ],
       [ 1.57515511, -0.53424844, -0.06119531, -0.80808981,  0.86430324,
        -0.16651776,  0.07796355, -1.53232841]])

In [51]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [59]:
a5 = np.random.randint(2,90,(6,5))
a5

array([[48, 32, 23, 56, 67],
       [71, 36, 14, 51, 33],
       [22, 60, 27, 60, 51],
       [59, 33,  3, 26, 52],
       [82, 54, 18, 43, 19],
       [36,  7, 44, 13, 35]])

In [62]:
a5[a5>40]

array([48, 56, 67, 71, 51, 60, 60, 51, 59, 52, 82, 54, 43, 44])

In [63]:
a5

array([[48, 32, 23, 56, 67],
       [71, 36, 14, 51, 33],
       [22, 60, 27, 60, 51],
       [59, 33,  3, 26, 52],
       [82, 54, 18, 43, 19],
       [36,  7, 44, 13, 35]])

In [65]:
a5[0,1] = 10000

In [66]:
a5

array([[   48, 10000,    23,    56,    67],
       [   71,    36,    14,    51,    33],
       [   22,    60,    27,    60,    51],
       [   59,    33,     3,    26,    52],
       [   82,    54,    18,    43,    19],
       [   36,     7,    44,    13,    35]])

In [72]:
a6 = np.random.randint(0,3,(3,3))

In [68]:
a7 = np.random.randint(0,3,(3,3))

In [73]:
a6

array([[1, 0, 1],
       [1, 0, 0],
       [1, 1, 2]])

In [70]:
a7

array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [74]:
a6*a7

array([[1, 0, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [75]:
a6@a7

array([[2, 1, 1],
       [1, 1, 1],
       [4, 1, 1]])

In [76]:
a6+100

array([[101, 100, 101],
       [101, 100, 100],
       [101, 101, 102]])

In [77]:
a6*2

array([[2, 0, 2],
       [2, 0, 0],
       [2, 2, 4]])

In [78]:
a6/0

C:\Users\hpadmin\AppData\Local\Temp\ipykernel_5256\1058679823.py:1: RuntimeWarning: divide by zero encountered in divide
  a6/0
C:\Users\hpadmin\AppData\Local\Temp\ipykernel_5256\1058679823.py:1: RuntimeWarning: invalid value encountered in divide
  a6/0


array([[inf, nan, inf],
       [inf, nan, nan],
       [inf, inf, inf]])

In [79]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [82]:
np.linspace(1,2,100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [83]:
np.linspace(1,2,100,retstep=True)

(array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
        1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
        1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
        1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
        1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
        1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
        1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
        1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
        1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
        1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
        1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
        1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
        1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
        1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
        1.70707071, 1.71717172, 1.72727273, 1.73

In [84]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
## data visuallization / graphs

In [87]:
!pip install cufflinks

     -------------------------------------- 81.7/81.7 kB 760.6 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68725 sha256=30d5c519faf4beece2840de44773fb8e243de23c7a2cb3021fa08b5fd785a654
  Stored in directory: c:\users\hpadmin\appdata\local\pip\cache\wheels\b1\8f\ec\b76ac80a14f3f5f59643cbc2eee7d78690b1bd158279f299dd
Successfully built cufflinks


In [88]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [89]:
cf.go_offline()

In [94]:
df = pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])
df

A         B         C
0  -1.107369  0.923983 -0.423371
1  -0.258647 -1.032156 -0.358497
2  -1.515512 -0.942786  0.136419
3  -2.828062  0.401329  0.386941
4   1.972131 -0.666796  0.543466
..       ...       ...       ...
95 -1.458516  0.190967  1.171492
96 -0.428984  0.039660 -0.225347
97  2.649929  0.114254 -1.016677
98  0.064939 -0.386996 -0.336183
99 -0.875562 -0.815323  0.712144

[100 rows x 3 columns]

In [95]:
df.iplot()

In [97]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))
df1

0
0   78
1    9
2   32
3   16
4   49
..  ..
95   9
96   6
97  31
98  84
99  53

[100 rows x 1 columns]

In [98]:
df1.iplot()

In [99]:
df

A         B         C
0  -1.107369  0.923983 -0.423371
1  -0.258647 -1.032156 -0.358497
2  -1.515512 -0.942786  0.136419
3  -2.828062  0.401329  0.386941
4   1.972131 -0.666796  0.543466
..       ...       ...       ...
95 -1.458516  0.190967  1.171492
96 -0.428984  0.039660 -0.225347
97  2.649929  0.114254 -1.016677
98  0.064939 -0.386996 -0.336183
99 -0.875562 -0.815323  0.712144

[100 rows x 3 columns]

In [102]:
df.iplot(x='A',y='B',mode='markers')

In [104]:
df2 = sns.load_dataset('titanic')
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [105]:
df2.iplot(x = 'age',y = 'fare',mode='markers')

In [107]:
df2.iplot(x = 'age',y = 'pclass',mode='markers')

In [108]:
df2.iplot(x = 'fare',y = 'pclass',mode='markers')

In [109]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [110]:
df2.iplot(kind='bar',x='sex',y = 'survived')