In [1]:
import pandas as pd

In [18]:
data = {
    'name':['deep','ankita','caspy','batman'],
    'salary':[100,200,300,400],
    'email_id':['deep@gmail.com','ankita@gmail.com','caspy@gmail.com','batman@gmail.com'],
    'address':['earth','earth','earth','gotham']
}

In [3]:
data

{'name': ['deep', 'ankita', 'caspy', 'batman'],
 'salary': [100, 200, 300, 400],
 'email_id': ['deep@gmail.com',
  'ankita@gmail.com',
  'caspy@gmail.com',
  'batman@gmail.com'],
 'address': ['earth', 'earth', 'earth', 'gotham']}

In [5]:
df = pd.DataFrame(data)
df

name  salary          email_id address
0    deep     100    deep@gmail.com   earth
1  ankita     200  ankita@gmail.com   earth
2   caspy     300   caspy@gmail.com   earth
3  batman     400  batman@gmail.com  gotham

In [6]:
df.iloc[1:3,1:3]

salary          email_id
1     200  ankita@gmail.com
2     300   caspy@gmail.com

In [19]:
data1 = {
    "pf_number":[123,345,455,232],
    "income_tax":[3434,12121,12121,12123],
    "mobile_number":[34343,77878,2121,898989],
    "courses":['fsds','python','java','blockchain']
}

In [8]:
data1

{'pf_number': [123, 345, 455, 232],
 'income_tax': [3434, 12121, 12121, 12123],
 'mobile_number': [34343, 77878, 2121, 898989],
 'courses': ['fsds', 'python', 'java', 'blockchain']}

In [9]:
df2 = pd.DataFrame(data1)

In [10]:
df2

pf_number  income_tax  mobile_number     courses
0        123        3434          34343        fsds
1        345       12121          77878      python
2        455       12121           2121        java
3        232       12123         898989  blockchain

In [11]:
df

name  salary          email_id address
0    deep     100    deep@gmail.com   earth
1  ankita     200  ankita@gmail.com   earth
2   caspy     300   caspy@gmail.com   earth
3  batman     400  batman@gmail.com  gotham

In [14]:
pd.concat([df,df2])

name  salary          email_id address  pf_number  income_tax  \
0    deep   100.0    deep@gmail.com   earth        NaN         NaN   
1  ankita   200.0  ankita@gmail.com   earth        NaN         NaN   
2   caspy   300.0   caspy@gmail.com   earth        NaN         NaN   
3  batman   400.0  batman@gmail.com  gotham        NaN         NaN   
0     NaN     NaN               NaN     NaN      123.0      3434.0   
1     NaN     NaN               NaN     NaN      345.0     12121.0   
2     NaN     NaN               NaN     NaN      455.0     12121.0   
3     NaN     NaN               NaN     NaN      232.0     12123.0   

   mobile_number     courses  
0            NaN         NaN  
1            NaN         NaN  
2            NaN         NaN  
3            NaN         NaN  
0        34343.0        fsds  
1        77878.0      python  
2         2121.0        java  
3       898989.0  blockchain

In [15]:
pd.concat([df,df2],axis=1)

name  salary          email_id address  pf_number  income_tax  \
0    deep     100    deep@gmail.com   earth        123        3434   
1  ankita     200  ankita@gmail.com   earth        345       12121   
2   caspy     300   caspy@gmail.com   earth        455       12121   
3  batman     400  batman@gmail.com  gotham        232       12123   

   mobile_number     courses  
0          34343        fsds  
1          77878      python  
2           2121        java  
3         898989  blockchain

In [20]:
data2 = {
    '0':['deep','ankita','caspy','batman'],
    '1':[100,200,300,400],
    '2':['deep@gmail.com','ankita@gmail.com','caspy@gmail.com','batman@gmail.com'],
    '3':['earth','earth','earth','gotham']
}

data3 = {
    '0':[123,345,455,232],
    '1':[3434,12121,12121,12123],
    '2':[34343,77878,2121,898989],
    '3':['fsds','python','java','blockchain']
}

In [21]:
df3 = pd.DataFrame(data2)
df4 = pd.DataFrame(data3)

In [22]:
df3

0    1                 2       3
0    deep  100    deep@gmail.com   earth
1  ankita  200  ankita@gmail.com   earth
2   caspy  300   caspy@gmail.com   earth
3  batman  400  batman@gmail.com  gotham

In [23]:
df4

0      1       2           3
0  123   3434   34343        fsds
1  345  12121   77878      python
2  455  12121    2121        java
3  232  12123  898989  blockchain

In [24]:
pd.concat([df3,df4])

0      1                 2           3
0    deep    100    deep@gmail.com       earth
1  ankita    200  ankita@gmail.com       earth
2   caspy    300   caspy@gmail.com       earth
3  batman    400  batman@gmail.com      gotham
0     123   3434             34343        fsds
1     345  12121             77878      python
2     455  12121              2121        java
3     232  12123            898989  blockchain

In [25]:
pd.concat([df3,df4],axis=1)

0    1                 2       3    0      1       2           3
0    deep  100    deep@gmail.com   earth  123   3434   34343        fsds
1  ankita  200  ankita@gmail.com   earth  345  12121   77878      python
2   caspy  300   caspy@gmail.com   earth  455  12121    2121        java
3  batman  400  batman@gmail.com  gotham  232  12123  898989  blockchain

In [26]:
data5 = {
    'emp_id':[101,102,103,104],
    'salary':[3434,223,3434,1212],
    'pf':[23,12,12,34]
}
data6 = {
    'emp_id':[101,102,106,107],
    'mob_no':[2323,23234,45454,878787],
    'house_no':[12,23,45,56]
}

In [27]:
df5 = pd.DataFrame(data5)
df6 = pd.DataFrame(data6)

In [28]:
df5

emp_id  salary  pf
0     101    3434  23
1     102     223  12
2     103    3434  12
3     104    1212  34

In [29]:
df6

emp_id  mob_no  house_no
0     101    2323        12
1     102   23234        23
2     106   45454        45
3     107  878787        56

In [30]:
pd.merge(df5,df6)

emp_id  salary  pf  mob_no  house_no
0     101    3434  23    2323        12
1     102     223  12   23234        23

In [31]:
pd.merge(df5,df6,how='left')

emp_id  salary  pf   mob_no  house_no
0     101    3434  23   2323.0      12.0
1     102     223  12  23234.0      23.0
2     103    3434  12      NaN       NaN
3     104    1212  34      NaN       NaN

In [32]:
df5

emp_id  salary  pf
0     101    3434  23
1     102     223  12
2     103    3434  12
3     104    1212  34

In [33]:
df6

emp_id  mob_no  house_no
0     101    2323        12
1     102   23234        23
2     106   45454        45
3     107  878787        56

In [34]:
pd.merge(df5,df6,how='right')

emp_id  salary    pf  mob_no  house_no
0     101  3434.0  23.0    2323        12
1     102   223.0  12.0   23234        23
2     106     NaN   NaN   45454        45
3     107     NaN   NaN  878787        56

In [35]:
pd.merge(df5,df6,how='right',on='emp_id')

emp_id  salary    pf  mob_no  house_no
0     101  3434.0  23.0    2323        12
1     102   223.0  12.0   23234        23
2     106     NaN   NaN   45454        45
3     107     NaN   NaN  878787        56

In [36]:
data7 = {
    'emp_id1':[101,102,103,104],
    'salary':[3434,223,3434,1212],
    'pf':[23,12,12,34]
}
data8 = {
    'emp_id2':[101,102,106,107],
    'mob_no':[2323,23234,45454,878787],
    'house_no':[12,23,45,56]
}

In [37]:
df7 = pd.DataFrame(data7)
df8 = pd.DataFrame(data8)

In [38]:
df7

emp_id1  salary  pf
0      101    3434  23
1      102     223  12
2      103    3434  12
3      104    1212  34

In [39]:
df8

emp_id2  mob_no  house_no
0      101    2323        12
1      102   23234        23
2      106   45454        45
3      107  878787        56

In [40]:
pd.merge(df7,df8)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [41]:
pd.merge(df7,df8,left_on='emp_id1',right_on='emp_id2')

emp_id1  salary  pf  emp_id2  mob_no  house_no
0      101    3434  23      101    2323        12
1      102     223  12      102   23234        23

In [42]:
pd.merge(df5,df6,on=['emp_id','salary'])

KeyError: 'salary'

In [53]:
data10 = {
    'emp_id1':[101,102,103,104],
    'salary1':[3434,223,3434,1212],
    'pf':[23,12,12,34]
}
data11 = {
    'emp_id2':[101,102,106,107],
    'salary2':[2323,23234,45454,878787],
    'house_no':[12,23,45,56]
}

In [54]:
df10 = pd.DataFrame(data10,index=['a','b','c','d'])
df11 = pd.DataFrame(data11,index=['a','b','d','e'])

In [55]:
df10

emp_id1  salary1  pf
a      101     3434  23
b      102      223  12
c      103     3434  12
d      104     1212  34

In [56]:
df11

emp_id2  salary2  house_no
a      101     2323        12
b      102    23234        23
d      106    45454        45
e      107   878787        56

In [51]:
pd.merge(df10,df11,on=['emp_id','salary'])

Empty DataFrame
Columns: [emp_id, salary, pf, house_no]
Index: []

In [57]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_no
a      101     3434  23    101.0   2323.0      12.0
b      102      223  12    102.0  23234.0      23.0
c      103     3434  12      NaN      NaN       NaN
d      104     1212  34    106.0  45454.0      45.0

In [58]:
df_titanic = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [59]:
df_titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [62]:
def check_Pclass(a):
    if a<3:
        return "poor"
    else:
        return "rich"

In [63]:
check_Pclass(1)

'poor'

In [64]:
check_Pclass(3)

'rich'

In [65]:
df_titanic['poor or rich'] = df_titanic['Pclass'].apply(check_Pclass)

In [66]:
df_titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked poor or rich  
0        0         A/5 21171   7.2500   NaN        S         rich  
1        0          PC 17599  71.2833   C85        C         poor  
2        0  STON/O2. 3101282   7.9250   NaN        S         rich  
3        0            113803  53.1000  C123        S         poor  
4        0            373450   8.0500   NaN        S         rich  
..     ...               ...      ...   ...      ...          ...  
886      0            211536  13.0000   NaN        S         poor  
887      0            112053  30.0000   B42        S         poor  
888      2        W./C. 6607  23.4500   NaN        S         rich  
889      0            111369  30.0000  C148        C         poor  
890      0            370376   7.7500   NaN        Q         rich  

[891 rows x 13 columns]

In [67]:
df_titanic['length of passenger name'] = df_titanic['Name'].apply(lambda x:len(x))

In [68]:
df_titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked poor or rich  \
0        0         A/5 21171   7.2500   NaN        S         rich   
1        0          PC 17599  71.2833   C85        C         poor   
2        0  STON/O2. 3101282   7.9250   NaN        S         rich   
3        0            113803  53.1000  C123        S         poor   
4        0            373450   8.0500   NaN        S         rich   
..     ...               ...      ...   ...      ...          ...   
886      0            211536  13.0000   NaN        S         poor   
887      0            112053  30.0000   B42        S         poor   
888      2        W./C. 6607  23.4500   NaN        S         rich   
889      0            111369  30.0000  C148        C         poor   
890      0            370376   7.7500   NaN        Q         rich   

     length of passenger name  
0                          23  
1                          51  
2                          22  
3                          44  
4                          24  
..                        ...  
886                        21  
887                        28  
888                        40  
889                        21  
890                        19  

[891 rows x 14 columns]

In [70]:
df_titanic.drop('length of passenger name',axis=1,inplace=True)

In [71]:
df_titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked poor or rich  
0        0         A/5 21171   7.2500   NaN        S         rich  
1        0          PC 17599  71.2833   C85        C         poor  
2        0  STON/O2. 3101282   7.9250   NaN        S         rich  
3        0            113803  53.1000  C123        S         poor  
4        0            373450   8.0500   NaN        S         rich  
..     ...               ...      ...   ...      ...          ...  
886      0            211536  13.0000   NaN        S         poor  
887      0            112053  30.0000   B42        S         poor  
888      2        W./C. 6607  23.4500   NaN        S         rich  
889      0            111369  30.0000  C148        C         poor  
890      0            370376   7.7500   NaN        Q         rich  

[891 rows x 13 columns]

In [72]:
df_titanic['length of name'] = df_titanic['Name'].apply(len)

In [73]:
df_titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked poor or rich  \
0        0         A/5 21171   7.2500   NaN        S         rich   
1        0          PC 17599  71.2833   C85        C         poor   
2        0  STON/O2. 3101282   7.9250   NaN        S         rich   
3        0            113803  53.1000  C123        S         poor   
4        0            373450   8.0500   NaN        S         rich   
..     ...               ...      ...   ...      ...          ...   
886      0            211536  13.0000   NaN        S         poor   
887      0            112053  30.0000   B42        S         poor   
888      2        W./C. 6607  23.4500   NaN        S         rich   
889      0            111369  30.0000  C148        C         poor   
890      0            370376   7.7500   NaN        Q         rich   

     length of name  
0                23  
1                51  
2                22  
3                44  
4                24  
..              ...  
886              21  
887              28  
888              40  
889              21  
890              19  

[891 rows x 14 columns]

In [74]:
df_titanic["square of fare"] = df_titanic['Fare'].apply(lambda x:x**2)

In [75]:
df_titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked poor or rich  \
0        0         A/5 21171   7.2500   NaN        S         rich   
1        0          PC 17599  71.2833   C85        C         poor   
2        0  STON/O2. 3101282   7.9250   NaN        S         rich   
3        0            113803  53.1000  C123        S         poor   
4        0            373450   8.0500   NaN        S         rich   
..     ...               ...      ...   ...      ...          ...   
886      0            211536  13.0000   NaN        S         poor   
887      0            112053  30.0000   B42        S         poor   
888      2        W./C. 6607  23.4500   NaN        S         rich   
889      0            111369  30.0000  C148        C         poor   
890      0            370376   7.7500   NaN        Q         rich   

     length of name  square of fare  
0                23       52.562500  
1                51     5081.308859  
2                22       62.805625  
3                44     2819.610000  
4                24       64.802500  
..              ...             ...  
886              21      169.000000  
887              28      900.000000  
888              40      549.902500  
889              21      900.000000  
890              19       60.062500  

[891 rows x 15 columns]

In [76]:
import numpy as np

In [77]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [78]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [79]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
l = [[1,2,3],[4,5,6]]

In [81]:
l[0][2]

3

In [85]:
a = np.array([3,4,5,6],ndmin=5)

In [86]:
a

array([[[[[3, 4, 5, 6]]]]])

In [88]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
arr.ndim

2

In [91]:
np.random.randint(1,10,(4,4))

array([[3, 8, 5, 4],
       [8, 5, 3, 2],
       [1, 5, 8, 5],
       [4, 9, 2, 1]])

In [92]:
np.random.randint(1,10,(4,4,2))

array([[[4, 1],
        [6, 2],
        [9, 4],
        [7, 4]],

       [[6, 5],
        [5, 5],
        [6, 4],
        [2, 6]],

       [[6, 6],
        [4, 8],
        [2, 6],
        [7, 8]],

       [[5, 1],
        [4, 6],
        [6, 6],
        [7, 9]]])